version: '2'

# Ignore this file, I've made it for my personal server.
# My blog runs along with several other sites, so I configure my nginx manually,
# instead of using a container.

services:
  # Postgres container
  postgres:
    # Getting official postgres image
    image: postgres:9.4
    # Taking password, databasename, etc from the env variables file
    env_file: ./backend/config/env
    # Creating a volume to preserve database data
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Backend API container
  backend:
    # Build by using Dockerfile in this directory
    build: ./backend
    # Name the container to easily attach to it
    container_name: backend
    # Create a volume so I could edit the code without rebuilding container
    volumes:
      - ./backend:/home/blog/backend
    # Taking password, databasename, etc from the env variables file    
    env_file: ./backend/config/env
    # Switch to this directory
    working_dir: /home/blog/backend
    # Run this command on start up, to launch a supervisor
    command: supervisord -n
    # Connect it to the postgres container
    depends_on:
      - postgres
    links:
      - postgres
    # Expose the ports
    ports:
      - '8000:8000'

  # Frontend container (static React files, index.html and bundle.js, served with nginx)
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/blog/frontend
    container_name: frontend
    working_dir: /home/blog/frontend
    container_name: frontend
    links:
      - backend
    ports:
      - '8080:8080'

